version: "3"
services:
  devtracker-bot:
    profiles: ["default"]
    image: "s0me-1:devtracker-bot"
    build:
      context: "."
      dockerfile: "Dockerfile"
    command: ["python", "bot.py"]
    env_file:
      - .env
    restart: always
    logging:
      driver: "local"
    volumes:
      - "./db:/db"
    secrets:
      - bot_token
      - api_token
      - api_base
      - sentry_dsn

  devtracker-bot-debug:
    profiles: ["debug"]
    image: "s0me-1:devtracker-bot-debug"
    build:
      context: "."
      dockerfile: "Dockerfile"
    command: ["python", "bot.py", "--log-level", "debug"]
    env_file:
      - .env
    volumes:
      - "./db:/db"
    secrets:
      - bot_token
      - api_token
      - api_base
      - debug_bot_token
      - debug_guild_id
      - sentry_dsn

secrets:
  bot_token:
    file: bot_token.sec
  api_token:
    file: api_token.sec
  api_base:
    file: api_base.sec
  debug_bot_token:
    file: debug_bot_token.sec
  debug_guild_id:
    file: debug_guild_id.sec
  sentry_dsn:
    file: sentry_dsn.sec
